apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
      - name: gke-test
        image: gcr.io/zevoice-180404/flask-assg-poc
        env:
            - name: SQLALCHEMY_DATABASE_URI
              value: postgresql://postgres:zemoso123@localhost:5432/task_db
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
      imagePullSecrets:
        - name: gcr-json-key
