version: "3"

services:
  api:
    build: .
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:zemoso123@host.docker.internal:5432/task_db
    ports:
      - 5000:5000
    network_mode: host
